/*

 HUD_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 3
   Tile set      : E:\GB_Dev\GB_Sprites\Capstone\tst\HUD.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define HUD_MapWidth 20
#define HUD_MapHeight 3
#define HUD_MapBank 0

extern unsigned char HUD_Map[];

/* End of HUD_MAP.H */
