/*

 RESULTSSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : E:\GB_Dev\GB_Sprites\Capstone\tst\ResultScreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ResultsScreenWidth 20
#define ResultsScreenHeight 18
#define ResultsScreenBank 0

extern unsigned char ResultsScreen[];

/* End of RESULTSSCREEN.H */
