/*

 ROADMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 32
   Tile set      : E:\GB_Dev\GB_Sprites\Capstone\tst\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define RoadMapWidth 20
#define RoadMapHeight 32
#define RoadMapBank 0

extern unsigned char RoadMap[];

/* End of ROADMAP.H */
