/*

 NUM_7.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 7 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char num_7[] =
{
  0xFF,0x00,0xFF,0xFE,0xFF,0x04,0xFF,0x08,
  0xFF,0x10,0xFF,0x20,0xFF,0x40,0xFF,0x80
};

/* End of NUM_7.C */
