/*

 NUM_2.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 2 to 2

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char num_2[] =
{
  0xFF,0x00,0xFF,0x7C,0xFF,0x82,0xFF,0x02,
  0xFF,0x0C,0xFF,0x30,0xFF,0x40,0xFF,0xFE
};

/* End of NUM_2.C */
