/*

 NUM_9.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 9 to 9

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char num_9[] =
{
  0xFF,0x00,0xFF,0x7C,0xFF,0x82,0xFF,0x82,
  0xFF,0x7E,0xFF,0x02,0xFF,0x02,0xFF,0x02
};

/* End of NUM_9.C */
