/*

 NUM_6.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 6 to 6

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char num_6[] =
{
  0xFF,0x00,0xFF,0x3C,0xFF,0x42,0xFF,0x80,
  0xFF,0xFC,0xFF,0x82,0xFF,0x82,0xFF,0x7C
};

/* End of NUM_6.C */
